# Generated by Django 5.0.1 on 2024-01-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_game_id_alter_ticket_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='set_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
